posts/urls.py
from django.contrib import admin
from django.urls import path,include
from posts_app import urls
from login_app import urls
from posts_app.views import about,contact
import django.contrib.auth.urls

urlpatterns = [
    
    path('admin/', admin.site.urls),
    path('accounts/',include('django.contrib.auth.urls')),
    path('posts/',include('posts_app.urls')),
    path('login/',include('login_app.urls')),
    path('about/',about.as_view(),name='about'),
    
]

posts_app/urls.py
from django.urls import path
from posts_app.views import createPost,displayPosts,postEdit,postDetailAndComment,createReply,deletePost,deleteComment,deleteReply,contact

urlpatterns = [
    
    path('',displayPosts,name='displayposts'),
    path(r'^newpost/$',createPost,name='createpost'),
    path(r'^postdetail/<int:pk>/$',postDetailAndComment,name='postdetails'),
    path(r'^postdetail/<int:pk>/editdetails/$',postEdit,name='editpost'),
    path(r'^postdetail/<int:pk>/reply/<int:pk2>/$',createReply,name='reply'),
    path(r'^postdetail/<int:pk>/deletepost/$',deletePost,name='deletepost'),
    path(r'^postdetail/<int:pk>/deletecomment/<int:pk2>$',deleteComment,name='deletecomment'),
    path(r'^postdetail/<int:pk>/reply/<int:pk2>/delete/<int:pk3>$',deleteReply,name='deletereply'),
    path(r'^contact/$',contact,name='contact'),
    
]

posts_app/models.py
from django.db import models
from django.conf import settings
from django.utils import timezone

class Post(models.Model):

    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete = models.CASCADE)
    title = models.CharField(blank=False, null=False, max_length=500)
    text = models.TextField()
    post_datetime = models.DateTimeField(null=True)

    def __str__(self):
        return self.title

class Comment(models.Model):
    
    post = models.ForeignKey(Post,on_delete = models.CASCADE)
    commentator = models.CharField(blank=False,null=False,max_length = 50)
    comment = models.CharField(blank=False,null=False,max_length=500)
    comment_datetime = models.DateTimeField(null=True)
    
    def __str__(self):
        return self.comment

class Reply(models.Model):
    
    post = models.ForeignKey(Post, on_delete = models.CASCADE)
    comment = models.ForeignKey(Comment, on_delete = models.CASCADE)
    respondent = models.CharField(blank=False,null=False,max_length= 15)
    reply = models.CharField(blank=False,null=False,max_length=500)
    reply_datetime = models.DateTimeField(null=True)
    
    def __str__(self):
        return self.reply

class Contact(models.Model):
    
    GeneralInformation = 'GI'
    I_am_a_liver_patient = 'IAALP'
    I_am_a_friend_family_of_a_liver_patient = 'IAAFFOALP'
    I_am_a_living_donor =  'IAALD'
    Information_regarding_organ_registration = 'IROR'
    Other = 'Other'
    
    reasons =  ((GeneralInformation, 'General Information'),
                (I_am_a_liver_patient, 'I am a liver patient'),
                (I_am_a_friend_family_of_a_liver_patient, 'I am a friend/family of a liver patient'),
                (I_am_a_living_donor, 'I am a living donor'),
                (Information_regarding_organ_registration, 'Information regarding organ registration'),
                (Other, 'Other'))
    
    first_name = models.CharField(blank=False, null=False,max_length=20, error_messages={'blank':'First name field cant be blank.'})
    last_name = models.CharField(blank=False,null=False,max_length=20)
    email = models.EmailField(blank=False,null=False)
    contact_no = models.IntegerField(blank=False,null=False)
    location = models.CharField(blank=False,null=False,max_length=50) 
    reason_for_contact = models.CharField(max_length=10, choices=reasons,default='GI')
    datetime = models.TimeField(null=True)
    
    def __str__(self):
        return self.first_name
       
     
    
    


    
    

posts_app/forms.py
from django import forms
from django.conf import settings
from django.utils import timezone
from .models import Post, Comment, Reply,  Contact

class PostForm(forms.ModelForm):
    
    title = forms.CharField(
                            widget = forms.TextInput(
                                    attrs={'class':'form-control','placeholder':'Title','size':95}
                                    )
                            )
    
    text = forms.CharField(
                            widget = forms.Textarea(
                                attrs = {
                                    'class': 'form-control','placeholder':'Text','rows':10,'cols':100
                                    }
                                )
                            )
    
    class Meta:
       model = Post
       fields = ('title', 'text')

class CommentForm(forms.ModelForm):
    
    comment = forms.CharField(
                            widget = forms.Textarea(
                                attrs = {
                                    'class': 'form-control', 'rows': 3, 'placeholder':'Comment'
                                    }
                                )
                            )
    commentator = forms.CharField(
                                widget = forms.TextInput(
                                    attrs = {
                                        'class': 'form-control', 'placeholder': 'Name', 'size': 5
                                    }
                                )
                                )
    class Meta:
        model = Comment
        fields = ('comment','commentator')

class ReplyForm(forms.ModelForm):
    
    reply = forms.CharField(
                            widget = forms.Textarea(
                                attrs = {
                                    'class':'form-control','rows':3,'placeholder':'Reply',
                                }
                            )
    )
    
    respondent = forms.CharField(
                                widget = forms.TextInput(
                                    attrs = {
                                        'class':'form-control','placeholder':'Name','size': 5
                                    }
                                )
    )
    
    class Meta:
        model = Reply
        fields = ('reply','respondent')

class ContactForm(forms.ModelForm):
    
    first_name = forms.CharField(
                                widget = forms.TextInput(
                                    attrs = {
                                        'class':'form-control','placeholder':'First Name','autofocus':True
                                    }
                                )
    )
    
    last_name = forms.CharField(
                                widget = forms.TextInput(
                                    attrs = {
                                        'class':'form-control','placeholder':'Last Name'
                                    }
                                )
    )
    
    email = forms.EmailField(
                            widget = forms.TextInput(
                                    attrs = {
                                        'class':'form-control','placeholder':'Email'
                                    }
                            )
    )
    
    contact_no = forms.IntegerField(
                                widget = forms.TextInput(
                                    attrs = {
                                        'class':'form-control','placeholder':'Contact No.'
                                    }
                                )
    )
    
    location = forms.CharField(
                                widget = forms.TextInput(
                                    attrs = {
                                        'class':'form-control','placeholder':'Location'
                                    } 
                                )
    )
    
    
    class Meta:
        model = Contact
        fields = ('first_name','last_name','email','contact_no','location','reason_for_contact')
        widgets = {'reason_for_contact': forms.RadioSelect(
                                                        attrs = {
                                                            'class':'form-check-input','required':'required'
                                                            }
                                                        )}

posts_app/views.py
from django.shortcuts import render, redirect, get_object_or_404, HttpResponseRedirect
from django.views.generic import TemplateView
from django.conf import settings
from django.utils import timezone
from django.core.paginator import Paginator, EmptyPage, InvalidPage
from django.contrib import messages
from posts import urls
from .models import Post, Comment, Reply, Contact
from .forms import PostForm, CommentForm, ReplyForm, ContactForm

class about(TemplateView):
    template_name = "about.html"    
    
def contact(request):
    
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            contact = form.save(commit=False)
            contact.datetime = timezone.now()
            contact.save()
            messages.success(request, 'Contact details submitted successfully!')
            return redirect('contact')
    else:
        form = ContactForm()
    context = { 'form': form }
    return render(request,'contact.html',context)
        
def createPost(request):                            # For creating new post

    if request.method == 'POST':                    # If request is POST, save the form data else generate a blank form
        form = PostForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.post_datetime = timezone.now()
            post.save()
            return redirect('displayposts')        
    else:
        post = PostForm()
    context = {'post': post}
    return render(request,'Posts/newpost.html',context)

def displayPosts(request):                          # For displaying all posts
    posts_list = Post.objects.all()  
    paginator = Paginator(posts_list,5)             # Paginator for allowing 5 posts on a page
    
    try:
        page = int(request.GET.get('page',1))
    except:
        page = 1
    
    try:
        posts = paginator.page(page)
    except(EmptyPage, InvalidPage):         
        posts = paginator.page(paginator.num_pages)
        
    return render(request,'Posts/posts.html',{ 'posts': posts, })

def postDetailAndComment(request, pk):              # view for generating template to display post and its comments and details. Also generates a form for comment submission
    post = get_object_or_404(Post, pk=pk)           # get post, comments and replies using pk of post
    comments = Comment.objects.filter(post_id=pk)  
    replies = Reply.objects.filter(post_id=pk)
    
    if request.method == "POST":
        form = CommentForm(request.POST)             # If the request is POST,save comment data and render template again.
        if form.is_valid():
            comment = form.save(commit=False)
            comment.comment_datetime = timezone.now()
            comment.post = get_object_or_404(Post,pk=pk)
            comment.save()
            form = CommentForm()                     # Clear the form after comment submission
            return render(request,'Posts/detail.html',{'post':post, 'form':form, 'comments':comments, 'replies':replies, })
    else:
        form = CommentForm()    
    context = { 'post': post, 'comments': comments, "form": form, "pk": pk, "replies":replies, }
    return render(request,'Posts/detail.html',context)

def postEdit(request, pk):                          # View for post editing.
    post = get_object_or_404(Post, pk=pk)           # Fetch the post using the post id.
    if request.method == 'POST':
        form = PostForm(request.POST,instance=post) # Passing the instance of post that needs editing.
        if form.is_valid:
            post = form.save(commit=False)
            post.author = request.user
            post.post_datetime = timezone.now()
            post.save()
            return redirect('postdetails',pk)       # Redirect to the page again with the edited post.
    else:
        form = PostForm(instance=post)              # In case of GET request, fetch the post instance for editing.
    return render(request,'Posts/edit.html',{ 'form': form , 'pk': pk })

def createReply(request, **kwargs):

    pk = kwargs['pk']                               # Fetching primary keys from the url.
    pk2 = kwargs['pk2']
    
    if request.method == 'POST':        
        Form = ReplyForm(request.POST)
        if Form.is_valid():
            reply = Form.save(commit=False)
            reply.post = get_object_or_404(Post, pk=pk)
            reply.comment = get_object_or_404(Comment, pk=pk2)
            reply.reply_datetime = timezone.now()
            reply.save()
            return redirect('postdetails',pk) 
    else:
        Form = ReplyForm()
    context = { 'form':Form, 'pk':pk, 'pk2':pk2, }    # Context dictionary when Reply Form is requested
    return render(request,'Posts/reply.html', context)

def deletePost(request, pk):    
    post = Post.objects.get(pk=pk)                  # Fetch the post which needs to be deleted 
    post.delete()
    return redirect('displayposts')

def deleteComment(request,pk,pk2):
    comment = Comment.objects.get(pk=pk2)           # Fetch the comment which needs to be deleted 
    comment.delete()
    return redirect('postdetails', pk)

def deleteReply(request,pk,pk2,pk3):
    reply = Reply.objects.get(pk=pk3)               # Fetch the reply which needs to be deleted
    reply.delete()
    return redirect('postdetails', pk)




    

posts_app/templates/Posts/comment.html
<html>
    {% extends 'index.html' %}
    {% block content %}
    <body>
        <div class="container-fluid">
        {% if user.is_authenticated %}
        <form method="POST">
            {% csrf_token %}
             {{ form }}
             <input type="submit" value="Post">
        </form>
        {% else %}
        <br>
        <hr>
            <p class="text-center"><a href="{% url 'login' %}">Login</a> to comment</p>
        {% endif %}
        </div>
    </body>
    {% endblock %}
</html>

posts_app/templates/Posts/detail.html
<html>
    {% extends 'index.html' %}
    {% block content %}
    <body> 
        <div class="container">
            <div class="shadow-sm p-3 mb-3 bg-white rounded">
                <h3>
                    {% if user.username|stringformat:"s" == post.author|stringformat:"s" %}
                    <div class="text-right">
                        <a href="{% url 'deletepost' pk=post.pk %}" class="text-decoration-none" onclick="return confirm('Are you sure?')">
                            <button type='button' class="btn btn-dark btn-sm">
                            <svg class="bi bi-trash" width="1em" height="1em" viewBox="0 0 16 16" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                                <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z"/>
                                <path fill-rule="evenodd" d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4L4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z"/>
                            </svg>                       
                            </button>
                            </a>
                        <a href="{% url 'editpost' pk=post.pk %}">
                            <button type='button' class="btn btn-warning btn-sm">
                            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16" width="16" height="16">
                            <path  d="M11.013 1.427a1.75 1.75 0 012.474 0l1.086 1.086a1.75 1.75 0 010 2.474l-8.61 8.61c-.21.21-.47.364-.756.445l-3.251.93a.75.75 0 01-.927-.928l.929-3.25a1.75 1.75 0 01.445-.758l8.61-8.61zm1.414 1.06a.25.25 0 00-.354 0L10.811 3.75l1.439 1.44 1.263-1.263a.25.25 0 000-.354l-1.086-1.086zM11.189 6.25L9.75 4.81l-6.286 6.287a.25.25 0 00-.064.108l-.558 1.953 1.953-.558a.249.249 0 00.108-.064l6.286-6.286z">
                            </path>
                            </svg>
                            </button>
                        </a>
                    </div>
                    {% else %}
                    <br>
                    {% endif %}
                    {{ post.title }}                         
                </h3>               
                <h6><p class="text-secondary">{{ post.author }}</p></h6>
                <small class="text-muted">
                    {{ post.post_datetime }}
                </small>
                <br>
                <div class="p-3 mb-2 bg-light text-dark">
                    <p>{{ post.text|linebreaksbr}}</p>
                </div>   
                <hr>
                <form method="POST">
                    {% csrf_token %}
                    {{ form.comment }}
                    <br>
                    {% if user.is_athenticated %}
                        <div class="col-sm-5">
                            <input class="form-control" type="text" name="commentator" value="{{ form.commentator.value|default:user.username }}" maxlength="15" size="5" id="id_commentator" required readonly>                    
                        </div>
                    {% else %}
                        <div class="col-sm-5">
                            {{ form.commentator }}                    
                        </div>
                    {% endif %}
                        <br>
                        <div class="float-right">
                            <button type='submit' class="btn btn-primary">Post</button>
                        </div>
                </form>
            <br>
            {% if comments %}
            <b>Comments :</b>
                {% for comment in comments %}
                <div class="shadow-sm p-1 mb-1 m-0 bg-white rounded">
                    <div class="card p-1 mb-1 m-1">
                        <div class="card-body m-0 mb-0 p-0">                           
                            <div class="alert alert-warning mb-0 m-1 p-2" role="alert">
                                <p>{{ comment.comment|linebreaksbr }}</p>
                            </div>
                            <div class="text-right m-0 mb-0 p-0">      
                                    <span class="badge badge-pill badge-light">
                                        {{ comment.commentator }}
                                    </span>&nbsp; | &nbsp;
                                <small>
                                    <i>{{ comment.comment_datetime }}</i>
                                    {% if post.author|stringformat:"s" == user.username|stringformat:"s" %}
                                    <a href="{% url 'deletecomment' pk=post.pk pk2=comment.pk %}" onclick="return confirm('Are you sure?')">
                                        <svg class="bi bi-trash" width="1em" height="1em" viewBox="0 0 16 16" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                                            <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z"/>
                                            <path fill-rule="evenodd" d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4L4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z"/>
                                        </svg>  
                                    </a>
                                    {% else %}
                                    <b>&nbsp;&nbsp;&nbsp;</b>
                                    {% endif %}
                                </small>
                            </div> 
                        </div> 
                    </div> 
                    <br>
                    <div class="container input-group-prepend m-1">
                        <a href="{% url 'reply' pk=post.pk pk2=comment.pk %}" class="text-decoration-none">   
                                <input class="form-control bg-light text-white" style="width:750px;" type="text" placeholder="Reply">
                        </a>&nbsp;&nbsp; 
                    </div>    
                        {% for reply in replies %}    
                                {% if reply.comment_id == comment.id %}    
                                <div class="shadow-sm p-1 mb-1 m-3 bg-white rounded">
                                    <div class="card p-1 m-0 mb-0">
                                        <div class="card-body mb-0 p-2 m-0">
                                            <br>
                                        <p>{{ reply.reply|linebreaksbr }}</p>
                                        </div> 
                                        {% if user.is_authenticated and post.author|stringformat:"s" == user.username|stringformat:"s" %}
                                            <p class="text-right p-0 mb-0 m-0">  
                                                <span class="badge badge-pill badge-light">{{ reply.respondent }}</span>&nbsp;|&nbsp;
                                                <small>
                                                    <i>{{ reply.reply_datetime }}</i>
                                                    <a href="{% url 'deletereply' pk=post.pk pk2=comment.pk pk3=reply.pk %}" onclick="return confirm('Are you sure?')">
                                                            <svg class="bi bi-trash" width="1em" height="1em" viewBox="0 0 16 16" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                                                                <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z"/>
                                                                <path fill-rule="evenodd" d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4L4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z"/>
                                                            </svg>  
                                                    </a>
                                                </small> &nbsp;&nbsp;
                                            </p>
                                        {% else %}
                                            <p class="text-right p-0 mb-0 m-1">                                            
                                                <span class="badge badge-pill badge-light">{{ reply.respondent }}</span>&nbsp;|&nbsp;                                           
                                                <small><i>{{ reply.reply_datetime }}</i></small> &nbsp;&nbsp;&nbsp;
                                            </p> 
                                        {% endif %}  
                                    </div>
                                </div>  
                                {% endif %}
                        {% endfor %}   
                </div> 
                <br>  
                {% endfor %}    
                {% else %}
                <hr>    
                    <p class="text-center">No comments yet</p>
                {% endif %}
            </div>        
        </div>
    </body>
    {% endblock %}
</html>

posts_app/templates/Posts/edit.html
<html>
    {% extends 'index.html' %}
    {% block content %}
    <head>
        <div class="shadow-sm p-3 mb-5 bg-white rounded d-flex justify-content-center">
            <h4>Edit Post</h4>        
        </div>
    </head>
    <body>
        <div class="container d-flex justify-content-center">
            <div class="form-group">
                <form method='POST'>
                    {% csrf_token %}
                    {% if user.is_authenticated %}
                    <div class="input-group mb-3">
                        <div class="input-group-prepend">
                            <span class="input-group-text" id="basic-addon1">Title : &nbsp&nbsp {{ form.title }}</span>
                        </div>
                    </div>
                    <div class="input-group mb-3">
                        <div class="input-group-prepend">
                            <span class="input-group-text" id="basic-addon1">Text : &nbsp&nbsp {{ form.text }}</span>
                        </div>
                    </div>
                    <div class="float-right">
                        <a href="{% url 'postdetails' pk=pk %}" class="text-decoration-none">
                            <button type='button' class="btn btn-dark">
                            Cancel
                            </button>
                        </a>
                        &nbsp;<input type='submit' class="btn btn-warning" value='Save'>
                    {% else %}
                        <p>User not logged in. Please login to create a new post.</p>
                    {% endif %}
                    </div>          
                </form>
                </div>
        </div>
    </body>
    {% endblock %}
</html>

posts_app/templates/Posts/newpost.html
<html>
    {% extends 'index.html' %}
    {% block content %}
    <head>
        <div class="shadow-sm p-3 mb-5 bg-white rounded d-flex justify-content-center">
            <h4>Create a new post</h4>
        </div>
    </head>     
    <body>
        <div class="container d-flex justify-content-center">
        <div class="form-group">
        <form method='POST'>
            {% csrf_token %}
            {% if user.is_authenticated %}
            <div class="input-group mb-3">
                <div class="input-group-prepend">
                    <span class="input-group-text" id="basic-addon1">{{ post.title }}</span>
                </div>
            </div>
            <div class="input-group mb-3">
                <div class="input-group-prepend">
                    <span class="input-group-text" id="basic-addon1">{{ post.text }}</span>
                </div>
            </div> 
                    <a href="{% url 'displayposts' %}"><button type='button' class="btn btn-dark">Cancel</button></a>
                    &nbsp;
                    <input type='submit' class="btn btn-warning" value='Post'>
            {% else %}
                <p>User not logged in. Please login to create a new post.</p>
                <a href="{% url 'displayposts' %}"><button type='button' class="btn btn-dark">Back</button></a>
            {% endif %}
                        
        </form>
        </div>
        </div>
    </body>
    {% endblock %}

</html>

posts_app/templates/Posts/reply.html
<html>
    {% extends 'index.html' %}
    {% block content %}
    <head>
    </head>
    <body>
        <br>
        <div class="container">
        <form method="POST">
            {% csrf_token %}
                {{ form.reply }}
                {% if user.is_authenticated %}
                <br>
                <div class="col-sm-5">  
                    <input class="form-control" type="text" name="respondent" maxlength="15" size="5" id="id_respondent" value="{{ form.respondent.value|default:user.username }}"  required readonly>         
                </div> 
                {% else %}
                <br>
                <div class="col-sm-5">    
                    {{ form.respondent }}
                </div>
                {% endif %}    
           <br>
            <div class="text-right">
                <a href="{% url 'postdetails' pk=pk %}" class="text-decoration-none">
                    <button type="button" class="btn btn-secondary btn-sm"> Cancel </button>
                </a>
                <input type="submit" class="btn btn-primary btn-sm" value="Post">
            </div>
        </form>
        </div>
    </body>
    {% endblock %}
</html>